dh = importdata('VER_hist_out.csv');
figure;
hold on;
xi = 0.1:.1:40;
[bv,bc] = hist(dh,xi);
[f,xi] = ksdensity(dh,xi);
bar(bc,bv/sum(bv),'EdgeColor','none','BarWidth',1);
cf = cumsum(f/10);
[ax,h1,h2] = plotyy(xi,f/10,xi,cf);
set(h1,'Color','r');
set(h1,'LineWidth',2);
set(h1,'LineStyle','-.');
set(get(ax(1),'Ylabel'),'String','PDF');
set(get(ax(2),'Ylabel'),'String','CDF');
set(h2,'Color','g');
set(h2,'LineWidth',2);
set(ax(1),'YTick',[0:0.004:0.04]);
set(ax(2),'YTick',[0:.1:1]);
grid(ax(2),'on');
set(ax,'XLim',[0,10]);
xlabel('Error (m)');